name: CI
on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
  Black:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black
  Pytest:
      runs-on: ubuntu-latest
      defaults: 
        run: 
          working-directory: backend
      steps:
        - name: Set up Python
          uses: actions/setup-python@main
          with:
            python-version: "3.10"
        - name: Run pytest summary
          run: pytest